version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

python:
  install:
    - method: flit
      extra_requirements:
        - docs

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true